### ISSUE TITLE
`open` function panics on error

### ISSUE THREAD

**Issue by Xion** [kosinix/raster#1]
The current implementation of public `open` function is calling an internal function and `unwrap`ing its result, rather than passing it upstream to the caller. Indeed, the function itself only ever returns `Ok`, and panics on error.

This is a critical API design issue that should be promptly addressed.

**Comment by kosinix** [comment]
Thats true. Im aware of this. The only reason its there is that I will be overhauling the IO APIs anyways to remove piston/image as a dependency and use plain decoders/encoders. But that would take some time.

@scottpleb Has plans for an immediate fix #2.
