### ISSUE TITLE
Strings aren't an ergonomic type for errors

### ISSUE THREAD

**Issue by scottpleb** [kosinix/raster#2]
I've noticed that various functions return `Result<T, String>`, which makes errors very impractical to consume. I'd be interested in creating a pull request to resolve this using enums, which I could likely have finished later today, if you'd be alright with that. I'd also be fixing #1 in the process of fixing this.

**Comment by kosinix** [comment]
Go for it! 

On a sidenote: What makes Result<T, String> impractical to consume?

**Comment by scottpleb** [comment]
While strings are adequate for error reporting in a CLI, when it comes to consuming them from other code, matching against them is unpleasant. For instance, let's say we have a `drive_car()` function that can error with `"Out of gas"`, `"Dead battery"`, or `"Car exploded"`. To handle these cases, we'd have to do something like:

```rust
match drive_car() {
    Ok(_) => enjoy_life(),
    Err(e) => match e.as_ref() {
        "Out of gas" => get_out_and_push(),
        "Dead battery" => jump_car(),
        "Car exploded" => duck_and_cover(),
        &_ => unreachable!()
    }
}
```

The issue is that each of the error messages has to be typed out by the user. If these error messages change, then all code that consumes them will also need to be changed. If any message is mistyped or otherwise invalid, or if a new error is added or one is removed, we'll have no way of knowing at compile time. Instead, we'll just end up falling through to that unreachable case at runtime, which is bad news. Fortunately, enums can be used to solve all of these issues:

```rust
enum CarError {
    OutOfGas,
    DeadBattery,
    Exploded
}

match drive_car() {
    Ok(_) => enjoy_life(),
    Err(e) => match e {
        CarError::OutOfGas => get_out_and_push(),
        CarError::DeadBattery => jump_car(),
        CarError::Exploded => duck_and_cover()
    }
}
```

This way, users will know at compile time that they've handled all error cases, and more than that, they have a type that tells them what all possible errors are instead of needing to have them explicitly documented. There's no need for the previous fall-through case, as the set of variants is both finite and clearly defined, and all of this is statically verified. As a cool bonus, auto-completion works on enum variants, which is a stark contrast from the previous situation of having to copy and paste strings around.

But wait, there's more! Some of the error messages you have, like the pixel out of bounds one, have variables in them. For users to match against a string like that, they'd have to do fiddly stuff; the best case scenario is using `starts_with`, and the worst case scenario is using regexes! If the user actually needs to get those numbers out of the string to use for something, then well, I think you get the idea. It's all much messier than it needs to be. It just so happens that enum variants aren't limited to just being names (if they were, they'd be more like C's enums, whereas they're actually more like C's tagged unions). We can give an enum variant a tuple (or even a struct) which lets us pass more information along:

```rust
enum RasterError {
    PixelOutOfBounds(i32, i32)
}
```

Now, with all of this in mind, we can put string error messages where they belong: at a higher layer.

```rust
fn print_error(e: RasterError) {
    match e {
        RasterError::PixelOutOfBounds(x, y) => println!("Getting a pixel at ({}, {}) that is out of bounds.", x, y)
    }
}
```

**Comment by kosinix** [comment]
Awesome! I learn something new in Rust today. Im excited to see what you'd come up with the pull req. Thanks for writing all that I really do appreciate it.
