### ISSUE TITLE
String-based flags should be replaced with enums

### ISSUE THREAD

**Issue by scottpleb** [kosinix/raster#4]
i.e. `"overlay"` should become `BlendMode::Overlay`

Between the discussion on Reddit and what I previously covered with error types, I'm sure you were expecting this. I've actually already finished implementing this; I'm only opening this issue to assure that efforts aren't needlessly duplicated. I would open the pull request for you to review, but I based it from the changes in my existing pull request, so it will have to wait.

**Comment by kosinix** [comment]
Prev pull req was  merged. Your good to go
